# Generated by Django 4.2.2 on 2023-08-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fan_app', '0005_rename_pub_date_comment_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
